# Volunteer Coin Project Foundation - PFP Token TOML
# Published: 2025

[[CURRENCIES]]
code="PFP"
issuer="7uY8eUotGcm1oXYj8xaFiBuk5saN9QYtqervA3vK7J6U"
image="https://raw.githubusercontent.com/Sholameister/volunteercoinproject.org/main/heart-coin-icon.png" # hosted via public IPFS fallback
desc="PFP - Pay It Forward & Protect - Rewarding volunteer time with real-world utility. Backed by BTC, gold, and compassion."
display_decimals=9
name="PFP"
status="live"
anchor_asset_type="crypto"
is_asset_anchored=false

[DOCUMENTATION]
ORG_NAME = "Volunteer Coin Project Foundation"
ORG_URL = "https://volunteercoinproject.org"
ORG_DESCRIPTION = "Total supply of 410M PFP tokens permanently locked and verified on-chain."

[[CURRENCIES]]
code = "P2"
issuer = "7uY8eUotGcm1oXYj8xaFiBuk5saN9QYtqervA3vK7J6U"
status = "live"
fixed_number = 410000000
is_unlimited = false
