# Volunteer Coin Project Foundation - PIF Token TOML
# Published: 2025

FEDERATION_SERVER="https://volunteercoinproject.org/federation"
AUTH_SERVER="https://volunteercoinproject.org/auth"
TRANSFER_SERVER="https://volunteercoinproject.org/sep6"
TRANSFER_SERVER_SEP0024="https://volunteercoinproject.org/sep24"
KYC_SERVER="https://volunteercoinproject.org/kyc"
WEB_AUTH_ENDPOINT="https://volunteercoinproject.org/auth"

[[CURRENCIES]]
code="PIF"
issuer="GAFWL7NRXEVJVDX7A6Z7OSVR2XUXC4EVCY7TXMBCIBY3B42XSEXX4GEV"
display_decimals=2
name="Pay It Forward Token"
desc="The official token of the Volunteer Coin Project Foundation (VCPF). Rewarding volunteerism with redeemable crypto backed by gold, Bitcoin, and purpose."
image="https://volunteercoinproject.org/assets/PIF_Token_Logo.png"
conditions="Redeemable at select retailers for food, gas, and essentials. Backed by community, gold, and BTC."
is_asset_anchored=true
anchor_asset_type="crypto"
fixed_number=1000000000
status="live"

[[PRINCIPALS]]
name="Volunteer Coin Project Foundation"
email="info@volunteercoinproject.org"
twitter="https://twitter.com/VolunteerCoin"
github="https://github.com/Sholameister"
website="https://volunteercoinproject.org"

[[VALIDATORS]]
alias="vcpf-main"
display_name="Volunteer Validator Node"
public_key="GAFWL7NRXEVJVDX7A6Z7OSVR2XUXC4EVCY7TXMBCIBY3B42XSEXX4GEV"
host="volunteercoinproject.org"
history="https://volunteercoinproject.org/history"

[[DOCUMENTATION]]
ORG_NAME="Volunteer Coin Project Foundation"
ORG_URL="https://volunteercoinproject.org"
ORG_DESCRIPTION="Nonprofit tokenizing kindness. PIF Tokens reward volunteers for their time and impact, redeemable for essentials and community goods. Transparency is our virtue."
ORG_LOGO="https://volunteercoinproject.org/assets/PIF_Token_Logo.png"
ORG_SUPPORT_EMAIL="info@volunteercoinproject.org"
ORG_LICENSING_URL="https://volunteercoinproject.org/legal"
ORG_TERMS_OF_SERVICE="https://volunteercoinproject.org/terms"
ORG_PRIVACY_POLICY="https://volunteercoinproject.org/privacy"
