# Volunteer Coin Project Foundation - PIF Token TOML
# Published: 2025

[[CURRENCIES]]
code="PIF"
issuer="GCGHHRDGEGLKFKXTJUD6RWGHWE3OYPEZZWOV5CDMUXGO3NKKGWLO62KF"
image="https://raw.githubusercontent.com/Sholameister/volunteercoinproject.org/main/heart-coin-icon.png" # hosted via public IPFS fallback
desc="Pay It Forward Token - Rewarding volunteer time with real-world utility. Backed by BTC, gold, and compassion."
display_decimals=2
name="Pay It Forward"
status="live"
anchor_asset_type="crypto"
is_asset_anchored=false
[DOCUMENTATION]
orgName = "Volunteer Coin Project Foundation"
orgURL = "https://volunteercoinproject.org"
orgDescription = "PIF is a fixed-supply utility token backed by mission-locked reserves and public use cases."

[ASSETS]
code = "PIF"
issuer = "GGCHHRDGEGLKFKXTJUD6RGWHVE3OYPEZZWOV5CDMUXGO3NKKGWLO62KF"
status = "finalized"
fixed_number = 950000000
is_unlimited = false
