# .github/workflows/firebase-hosting-deploy.yml
name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo files and firebase.json
        run: |
          echo "PWD:" && pwd
          echo "Listing files:" && ls -la
          echo "firebase.json contents:" && cat firebase.json || echo "firebase.json missing"

      # LIVE on push to main
      - name: Deploy LIVE (push to main)
        if: github.event_name == 'push'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOVEBUTTON_HEAVEN }}
          projectId: lovebutton-heaven
          site: lovebutton-heaven
          channelId: live

      # PREVIEW on PRs
      - name: Deploy PREVIEW (pull request)
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOVEBUTTON_HEAVEN }}
          projectId: lovebutton-heaven
          site: lovebutton-heaven
          channelId: pr-${{ github.event.number }}
          expires: 7d
